# Generated by Django 3.0.3 on 2020-02-11 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=30)),
                ('last_name', models.CharField(max_length=20)),
                ('company_name', models.CharField(max_length=80)),
                ('age', models.PositiveIntegerField()),
                ('city', models.CharField(max_length=30)),
                ('state', models.CharField(max_length=50)),
                ('zip', models.PositiveIntegerField(max_length=12)),
                ('email', models.EmailField(max_length=200, unique=True)),
                ('web', models.CharField(max_length=100)),
            ],
        ),
    ]
