# Generated by Django 3.0.3 on 2020-02-11 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdata',
            name='zip',
            field=models.CharField(max_length=12),
        ),
    ]
